In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('ts_20211126.csv')
df

ParserError: ignored

In [ ]:
sensor01 = []
sensor02 = []
manaDat = []

for i in range(0,len(df),30):
    sensor01 += [df['sensor01'][i]]
    sensor02 += [df['sensor02'][i]]
    manaDat += [df['manaDat'][i]]

In [ ]:
for i in range(len(manaDat)):
    manaDat[i] = str(manaDat[i])[:12]
print(manaDat)

['202106101654', '202106101655', '202106101656', '202106101657', '202106101658', '202106101659', '202106101700', '202106101701', '202106101702', '202106101703', '202106101704', '202106101705', '202106101706', '202106101707', '202106101708', '202106101709', '202106101710', '202106101711', '202106101712', '202106101713', '202106101714', '202106101715', '202106101716', '202106101717', '202106101718', '202106101719', '202106101720', '202106101721', '202106101722', '202106101723', '202106101724', '202106101725', '202106101726', '202106101727', '202106101728', '202106101729', '202106101730', '202106101731', '202106101732', '202106101733', '202106101734', '202106101735', '202106101736', '202106101737', '202106101738', '202106101739', '202106101740', '202106101741', '202106101742', '202106101743', '202106101744', '202106101745', '202106101746', '202106101747', '202106101748', '202106101749', '202106101750', '202106101751', '202106101752', '202106101753', '202106101754', '202106101755', '202106101756', '202106101757', '202106101758', '202106101759', '202106101800', '202106101801', '202106101802', '202106101803', '202106101804', '202106101805', '202106101806', '202106101807', '202106101808', '202106101809', '202106101810', '202106101811', '202106101812', '202106101813', '202106101814', '202106101815', '202106101816', '202106101817', '202106101818', '202106101819', '202106101820', '202106101821', '202106101822', '202106101823', '202106101824', '202106101825', '202106101826', '202106101827', '202106101828', '202106101829', '202106101830', '202106101831', '202106101832', '202106101833', '202106101834', '202106101835', '202106101836', '202106101837', '202106101838', '202106101839', '202106101840', '202106101841', '202106101842', '202106101843', '202106101844', '202106101845', '202106101846', '202106101847', '202106101848', '202106101849', '202106101850', '202106101851', '202106101852', '202106101853', '202106101854', '202106101855', '202106101856', '202106101857', '202106101858', '202106101859', '202106101900', '202106101901', '202106101902', '202106101903', '202106101904', '202106101905', '202106101906', '202106101907', '202106101908', '202106101909', '202106101910', '202106101911', '202106101912', '202106101913', '202106101914', '202106101915', '202106101916', '202106101917', '202106101918', '202106101919', '202106101920', '202106101921', '202106101922', '202106101923', '202106101924', '202106101925', '202106101926', '202106101927', '202106101928', '202106101929', '202106101930', '202106101931', '202106101932', '202106101933', '202106101934', '202106101935', '202106101936', '202106101937', '202106101938', '202106101939', '202106101940', '202106101941', '202106101942', '202106101943', '202106101944', '202106101945', '202106101946', '202106101947', '202106101948', '202106101949', '202106101950', '202106101951', '202106101952', '202106101953', '202106101954', '202106101955', '202106101956', '202106101957', '202106101958', '202106101959', '202106102000', '202106102001', '202106102002', '202106102003', '202106102004', '202106102005', '202106102006', '202106102007', '202106102008', '202106102009', '202106102010', '202106102011', '202106102012', '202106102013', '202106102014', '202106102015', '202106102016', '202106102017', '202106102018', '202106102019', '202106102020', '202106102021', '202106102022', '202106102023', '202106102024', '202106102025', '202106102026', '202106102027', '202106102028', '202106102029', '202106102030', '202106102031', '202106102032', '202106102033', '202106102034', '202106102035', '202106102036', '202106102037', '202106102038', '202106102039', '202106102040', '202106102041', '202106102042', '202106102043', '202106102044', '202106102045', '202106102046', '202106102047', '202106102048', '202106102049', '202106102050', '202106102051', '202106102052', '202106102053', '202106102054', '202106102055', '202106102056', '202106102057', '202106102058', '202106102059', '202106102100', '202106102101', '202106102102', '202106102103', '202106102104', '202106102105', '202106102106', '202106102107', '202106102108', '202106102109', '202106102110', '202106102111', '202106102112', '202106102113', '202106102114', '202106102115', '202106102116', '202106102117', '202106102118', '202106102119', '202106102120', '202106102121', '202106102122', '202106102123', '202106102124', '202106102125', '202106102126', '202106102127', '202106102128', '202106102129', '202106102130', '202106102131', '202106102132', '202106102133', '202106102134', '202106102135', '202106102136', '202106102137', '202106102138', '202106102139', '202106102140', '202106102141', '202106102142', '202106102143', '202106102144', '202106102145', '202106102146', '202106102147', '202106102148', '202106102149', '202106102150', '202106102151', '202106102152', '202106102153', '202106102154', '202106102155', '202106102156', '202106102157', '202106102158', '202106102159', '202106102200', '202106102201', '202106102202', '202106102203', '202106102204', '202106102205', '202106102206', '202106102207', '202106102208', '202106102209', '202106102210', '202106102211', '202106102212', '202106102213', '202106102214', '202106102215', '202106102216', '202106102217', '202106102218', '202106102219', '202106102220', '202106102221', '202106102222', '202106102223', '202106102224', '202106102225', '202106102226', '202106102227', '202106102228', '202106102229', '202106102230', '202106102231', '202106102232', '202106102233', '202106102234', '202106102235', '202106102236', '202106102237', '202106102238', '202106102239', '202106102240', '202106102241', '202106102242', '202106102243', '202106102244', '202106102245', '202106102246', '202106102247', '202106102248', '202106102249', '202106102250', '202106102251', '202106102252', '202106102253', '202106102254', '202106102255', '202106102256', '202106102257', '202106102258', '202106102259', '202106102300', '202106102301', '202106102302', '202106102303', '202106102304', '202106102305', '202106102306', '202106102307', '202106102308', '202106102309', '202106102310', '202106102311', '202106102312', '202106102313', '202106102314', '202106102315', '202106102316', '202106102317', '202106102318', '202106102319', '202106102320', '202106102321', '202106102322', '202106102323', '202106102324', '202106102325', '202106102326', '202106102327', '202106102328', '202106102329', '202106102330', '202106102331', '202106102332', '202106102333', '202106102334', '202106102335', '202106102336', '202106102337', '202106102338', '202106102339', '202106102340', '202106102341', '202106102342', '202106102343', '202106102344', '202106102345', '202106102346', '202106102347', '202106102348', '202106102349', '202106102350', '202106102351', '202106102352', '202106102353', '202106102354', '202106102355', '202106102356', '202106102357', '202106102358', '202106102359']

In [ ]:
df2=pd.DataFrame([manaDat,sensor01, sensor02])
df2

,0,1,2,3,4,5,6,7,8,9,...,416,417,418,419,420,421,422,423,424,425
0,202106101654,202106101655,202106101656,202106101657,202106101658,202106101659,202106101700,202106101701,202106101702,202106101703,...,202106102350,202106102351,202106102352,202106102353,202106102354,202106102355,202106102356,202106102357,202106102358,202106102359
1,21.28,21.22,21.27,21.25,21.3,21.37,21.41,21.49,21.55,21.59,...,22.51,22.54,22.58,22.64,22.66,22.69,22.72,22.75,22.79,22.84
2,72.4,76.37,78.45,79.49,80.0,80.13,80.28,80.13,80.02,79.41,...,79.0,78.81,78.63,78.49,78.33,78.17,78.04,77.83,77.71,77.55

In [ ]:
df2=df2.transpose()
df2

                0      1      2
0    202106101654  21.28   72.4
1    202106101655  21.22  76.37
2    202106101656  21.27  78.45
3    202106101657  21.25  79.49
4    202106101658   21.3   80.0
..            ...    ...    ...
421  202106102355  22.69  78.17
422  202106102356  22.72  78.04
423  202106102357  22.75  77.83
424  202106102358  22.79  77.71
425  202106102359  22.84  77.55

[426 rows x 3 columns]

In [ ]:
df2=df2.rename(columns={0:'date',1:'temp',2:'humi'})
df2

             date   temp   humi
0    202106101654  21.28   72.4
1    202106101655  21.22  76.37
2    202106101656  21.27  78.45
3    202106101657  21.25  79.49
4    202106101658   21.3   80.0
..            ...    ...    ...
421  202106102355  22.69  78.17
422  202106102356  22.72  78.04
423  202106102357  22.75  77.83
424  202106102358  22.79  77.71
425  202106102359  22.84  77.55

[426 rows x 3 columns]

In [ ]:
df2.index = pd.to_datetime(df2['date'])
df2=df2.drop('date',axis=1)
df2

                      temp   humi
date
2021-06-10 16:54:00  21.28   72.4
2021-06-10 16:55:00  21.22  76.37
2021-06-10 16:56:00  21.27  78.45
2021-06-10 16:57:00  21.25  79.49
2021-06-10 16:58:00   21.3   80.0
...                    ...    ...
2021-06-10 23:55:00  22.69  78.17
2021-06-10 23:56:00  22.72  78.04
2021-06-10 23:57:00  22.75  77.83
2021-06-10 23:58:00  22.79  77.71
2021-06-10 23:59:00  22.84  77.55

[426 rows x 2 columns]

In [ ]:
df2.to_csv('210610.csv')