In [2]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.formula.api import ols

plt.rc('font',family='Malgun Gothic')
plt.rcParams['axes.unicode_minus']=False

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [18]:
#데이터 읽어오기
df=pd.read_csv('총데이터4월_1월.csv')
df

,date,soc,dcA,dcV,minTemp,maxTemp,차이*총량,P(kw),temp
0,2021-04-09 00:00:00,64.0,0.1,754.6,23.0,24.0,0.0,0.07546,23.5
1,2021-04-09 00:01:00,64.0,0.1,754.6,23.0,24.0,0.0,0.07546,23.5
2,2021-04-09 00:02:00,64.0,0.0,754.6,23.0,24.0,0.0,0.00000,23.5
3,2021-04-09 00:03:00,64.0,-0.1,754.6,23.0,24.0,0.0,-0.07546,23.5
4,2021-04-09 00:04:00,64.0,0.0,754.5,23.0,24.0,0.0,0.00000,23.5
...,...,...,...,...,...,...,...,...,...
351824,2022-01-28 06:46:00,40.0,0.2,717.6,21.0,20.0,0.0,0.14352,20.5
351825,2022-01-28 06:47:00,40.0,0.2,717.6,21.0,20.0,0.0,0.14352,20.5
351826,2022-01-28 06:48:00,40.0,0.2,717.6,21.0,20.0,0.0,0.14352,20.5
351827,2022-01-28 06:49:00,40.0,0.3,717.6,21.0,20.0,0.0,0.21528,20.5
351828,2022-01-28 06:50:00,40.0,0.3,717.6,21.0,20.0,0.0,0.21528,20.5

In [19]:
# 일시를 datetime형으로 변환
df.index = pd.to_datetime(df['date'])
# 기존 컬럼 삭제
df = df.drop(['date'], axis=1)
df

                      soc  dcA    dcV  minTemp  maxTemp  차이*총량    P(kw)  temp
date
2021-04-09 00:00:00  64.0  0.1  754.6     23.0     24.0    0.0  0.07546  23.5
2021-04-09 00:01:00  64.0  0.1  754.6     23.0     24.0    0.0  0.07546  23.5
2021-04-09 00:02:00  64.0  0.0  754.6     23.0     24.0    0.0  0.00000  23.5
2021-04-09 00:03:00  64.0 -0.1  754.6     23.0     24.0    0.0 -0.07546  23.5
2021-04-09 00:04:00  64.0  0.0  754.5     23.0     24.0    0.0  0.00000  23.5
...                   ...  ...    ...      ...      ...    ...      ...   ...
2022-01-28 06:46:00  40.0  0.2  717.6     21.0     20.0    0.0  0.14352  20.5
2022-01-28 06:47:00  40.0  0.2  717.6     21.0     20.0    0.0  0.14352  20.5
2022-01-28 06:48:00  40.0  0.2  717.6     21.0     20.0    0.0  0.14352  20.5
2022-01-28 06:49:00  40.0  0.3  717.6     21.0     20.0    0.0  0.21528  20.5
2022-01-28 06:50:00  40.0  0.3  717.6     21.0     20.0    0.0  0.21528  20.5

[351829 rows x 8 columns]

In [20]:
#년 월 데이터로 만들기
pr_m=pd.period_range(start = '2021-04',end= None, periods= 10, freq= 'M' )
pr_m

PeriodIndex(['2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09',
             '2021-10', '2021-11', '2021-12', '2022-01'],
            dtype='period[M]')

In [16]:
#상관 계수
for m in range(10):
    df.loc[str(pr_m[m])].corr()